apiVersion: v1
kind: Service
metadata:
  name: simple-http-prometheus 
  namespace: henrod
  annotations:
    ad.datadoghq.com/endpoints.check_names: '["openmetrics"]'
    ad.datadoghq.com/endpoints.init_configs: '[{}]'
    ad.datadoghq.com/endpoints.instances: |
      [{
         "metrics": ["*"],
         "namespace": "henrod",
         "prometheus_url": "http://%%host%%:2112/metrics",
         "send_distribution_buckets": true,
         "max_returned_metrics": 2000,
         "send_monotonic_counter": true,
         "labels_mapper": ""
       }]
spec:
  selector:
    app: simple-http-prometheus
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
    - protocol: TCP
      port: 2112
      targetPort: 2112
      name: metrics
